# """
# Django settings for backend project.

# Generated by 'django-admin startproject' using Django 6.0.2.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """

# from pathlib import Path
# import os
# from datetime import timedelta

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-zedp_=pj+frk-x5*y$dsqk0%*50rk1kyddg=9(-4-h$*(2-hjj'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []

# CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#      'hypermodest-irena-washy.ngrok-free.dev', 
# ]
# CORS_ALLOW_CREDENTIALS = True

# APPEND_SLASH = True

# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'rest_framework_simplejwt',
#      "corsheaders",

#     # apps
#     'dashboard',
#     'inventory',
#     'notifications',
#     'orders',
#     'reports',
#     'users',
#     'mpesa',
#     'settings',
#     'sslserver',
# ]

# if DEBUG:
#     SESSION_COOKIE_SECURE = False
#     CSRF_COOKIE_SECURE = False

# # Force HTTPS in production
# SECURE_SSL_REDIRECT = False  # Set to True in production
# SESSION_COOKIE_SECURE = True  # Set to True in production
# CSRF_COOKIE_SECURE = True     # Set to True in production

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
# }

# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'backend.urls'


# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'backend.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# # ============= ADD THIS SECTION =============
# # In settings.py, update MPESA_CONFIG:

# MPESA_CONFIG = {
#     'CONSUMER_KEY': 'DiyO3HgTpc5PuM1xRNdBbXppU7YWE1vuYnlvGZMRBVwzwZcE',
#     'CONSUMER_SECRET': '23XZzrSz9gs4hg5eRsTXvp3oYHGF9OvRBIZQafef14SOFlpStiyfAA070pR4MrQG',
#     'BUSINESS_SHORTCODE': '174379',
#     'PASSKEY': 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
#     # IMPORTANT: For sandbox testing, use a real URL. If testing locally, use ngrok
#     'CALLBACK_URL': 'https://hypermodest-irena-washy.ngrok-free.dev/api/mpesa/callback/',  # MUST be HTTPS
#     'ENVIRONMENT': 'sandbox',
# }

# # Verify the callback URL is HTTPS (required by M-Pesa)
# if MPESA_CONFIG['ENVIRONMENT'] == 'sandbox':
#     MPESA_API_URL = 'https://sandbox.safaricom.co.ke'
# else:
#     MPESA_API_URL = 'https://api.safaricom.co.ke'

# # Add this for debugging
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#         'file': {
#             'class': 'logging.FileHandler',
#             'filename': 'mpesa_debug.log',
#         },
#     },
#     'loggers': {
#         'mpesa': {
#             'handlers': ['console', 'file'],
#             'level': 'INFO',
#         },
#     },
# }

# # Add CORS settings for your frontend
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # Your React/Vue frontend
#     "http://localhost:5500",   # Live Server
#     "http://127.0.0.1:5500",  # Live Server alternative
#     "http://localhost:8000",   # Django dev server
# ]

# # For testing only - you can enable this temporarily
# # CORS_ALLOW_ALL_ORIGINS = True  # Uncomment only for testing

# # Add CORS headers
# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
# ]

# settings.py - Updated for Session/Cookie Authentication

# import os
# from pathlib import Path
# from datetime import timedelta

# BASE_DIR = Path(__file__).resolve().parent.parent

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-zedp_=pj+frk-x5*y$dsqk0%*50rk1kyddg=9(-4-h$*(2-hjj'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# # IMPORTANT: Add all allowed hosts
# # ALLOWED_HOSTS = [
# #     'localhost',
# #     '127.0.0.1',
# #     '0.0.0.0',
# #     'glow-mart-backend.onrender.com',  # ← ADD THIS
# #     '.onrender.com',  # Allow all Render subdomains
# #     'hypermodest-irena-washy.ngrok-free.dev',
# #     '.ngrok-free.dev',
# #     '.ngrok.io',
# # ]

# ALLOWED_HOSTS = [
#     'glow-mart-backend-1.onrender.com',
#     '.onrender.com',
#     'hypermodest-irena-washy.ngrok-free.dev',
# ]

# # ============= CORS SETTINGS =============
# CORS_ALLOW_ALL_ORIGINS = False

# CORS_ALLOWED_ORIGINS = [
#     "https://glow-mart.vercel.app",  # ← ADD YOUR VERCEL URL
#     "https://glow-mart-frontend.vercel.app",  # Replace with actual URL
#     "http://localhost:5173",
#     "http://localhost:3000",
#     "http://localhost:5500",
#     "http://127.0.0.1:5173",
#     "http://127.0.0.1:3000",
#     "https://hypermodest-irena-washy.ngrok-free.dev",
# ]

# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
# ]

# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

# # CRITICAL: Allow credentials (cookies)
# CORS_ALLOW_CREDENTIALS = True

# CORS_PREFLIGHT_MAX_AGE = 86400

# # CSRF Trusted Origins
# # CSRF_TRUSTED_ORIGINS = [
# #     "https://glow-mart.vercel.app",  # ← ADD YOUR VERCEL URL
# #     "https://your-frontend.vercel.app",  # Replace with actual URL
# #     "http://localhost:5173",
# #     "http://localhost:3000",
# #     "http://127.0.0.1:5173",
# #     "https://hypermodest-irena-washy.ngrok-free.dev",
# #     "https://*.ngrok-free.dev",
# #     "https://*.onrender.com",  # Allow Render backends
# # ]

# CSRF_TRUSTED_ORIGINS = [
#     "https://glow-mart.vercel.app",
#     "https://glow-mart-frontend.vercel.app",
#     "https://hypermodest-irena-washy.ngrok-free.dev",
# ]
# # ============= SESSION/COOKIE SETTINGS (FIXED FOR CROSS-ORIGIN) =============
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# SESSION_COOKIE_AGE = 86400
# SESSION_COOKIE_HTTPONLY = True

# # 🔴 MUST be None for cross-origin (Vercel ↔ Render)
# SESSION_COOKIE_SAMESITE = 'None'
# CSRF_COOKIE_SAMESITE = 'None'

# # 🔴 MUST be True in production (HTTPS)
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# SESSION_SAVE_EVERY_REQUEST = True
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF_COOKIE_HTTPONLY = False
# CSRF_USE_SESSIONS = False
# CSRF_COOKIE_NAME = 'csrftoken'

# APPEND_SLASH = False


# # ============= ASGI/WebSocket Settings =============
# ASGI_APPLICATION = "backend.asgi.application"

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     },
# }

# # Application definition
# INSTALLED_APPS = [
#     'daphne',
#     'corsheaders',
#     'channels',
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',  # Required for sessions
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
    
#     # Third party apps
#     'rest_framework',
#     'rest_framework_simplejwt',  # COMMENT OUT - Not needed for session auth
#     'sslserver',
    
#     # Custom apps
#     'dashboard',
#     'inventory',
#     'notifications',
#     'orders',
#     'reports',
#     'users',
#     'mpesa',
#     'settings',
#     'whitenoise',
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this
#     'django.contrib.sessions.middleware.SessionMiddleware',  # Required for sessions
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',  # Required for CSRF protection
#     'django.contrib.auth.middleware.AuthenticationMiddleware',  # Required for auth
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'backend.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'backend.wsgi.application'

# # Database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# # Password validation
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# # Internationalization
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'Africa/Nairobi'
# USE_I18N = True
# USE_TZ = True

# # Static files (CSS, JavaScript, Images)
# STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# # Media files
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # Default primary key field type
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # ============= REST FRAMEWORK SETTINGS (UPDATED FOR SESSION AUTH) =============
# # settings.py - Update REST_FRAMEWORK settings
# REST_FRAMEWORK = {
#    'DEFAULT_AUTHENTICATION_CLASSES': (
#     'rest_framework.authentication.SessionAuthentication',
# ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 20,
#     'DEFAULT_THROTTLE_CLASSES': [],  # Disable throttling completely
#     # OR increase the limits:
#     'DEFAULT_THROTTLE_RATES': {
#         'anon': '1000/minute',  # Increased from 100/day
#         'user': '10000/minute',  # Increased from 1000/day
#     },
# }

# # ============= AUTHENTICATION BACKENDS =============
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',  # Default backend
# ]

# # ============= M-Pesa Configuration =============
# MPESA_API_URL = 'https://sandbox.safaricom.co.ke'

# MPESA_CONFIG = {
#     'CONSUMER_KEY': 'DiyO3HgTpc5PuM1xRNdBbXppU7YWE1vuYnlvGZMRBVwzwZcE',
#     'CONSUMER_SECRET': '23XZzrSz9gs4hg5eRsTXvp3oYHGF9OvRBIZQafef14SOFlpStiyfAA070pR4MrQG',
#     'BUSINESS_SHORTCODE': '174379',
#     'PASSKEY': 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
#     'CALLBACK_URL': 'https://glow-mart-backend-1.onrender.com/api/mpesa/callback/',
#     'TIMEOUT_URL': 'https://glow-mart-backend-1.onrender.com/api/mpesa/timeout/',
#     'RESULT_URL': 'https://glow-mart-backend-1.onrender.com/api/mpesa/result/',
# }

# # ============= Orders Settings =============
# ORDER_STATUS_CHOICES = [
#     ('pending', 'Pending'),
#     ('processing', 'Processing'),
#     ('completed', 'Completed'),
#     ('cancelled', 'Cancelled'),
#     ('refunded', 'Refunded'),
# ]

# PAYMENT_STATUS_CHOICES = [
#     ('pending', 'Pending'),
#     ('processing', 'Processing'),
#     ('completed', 'Completed'),
#     ('failed', 'Failed'),
#     ('refunded', 'Refunded'),
# ]

# # ============= Logging Configuration =============
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {asctime} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'simple',
#         },
#         'file': {
#             'class': 'logging.FileHandler',
#             'filename': 'debug.log',
#             'formatter': 'verbose',
#         },
#         'mpesa_file': {
#             'class': 'logging.FileHandler',
#             'filename': 'mpesa_debug.log',
#             'formatter': 'verbose',
#         },
#         'orders_file': {
#             'class': 'logging.FileHandler',
#             'filename': 'orders.log',
#             'formatter': 'verbose',
#         },
#     },
#     'loggers': {
#         'mpesa': {
#             'handlers': ['console', 'mpesa_file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#         'orders': {
#             'handlers': ['console', 'orders_file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#         'django': {
#             'handlers': ['console', 'file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#         'corsheaders': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }

# # ============= Security Settings =============
# if not DEBUG:
#     SECURE_SSL_REDIRECT = False  # ❌ keep OFF on Render
#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True

#     SECURE_BROWSER_XSS_FILTER = True
#     SECURE_CONTENT_TYPE_NOSNIFF = True
#     X_FRAME_OPTIONS = 'DENY'

#     SECURE_HSTS_SECONDS = 0  # ❌ disable HSTS for now (important)

# # ============= Email Configuration =============
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# DEFAULT_FROM_EMAIL = 'GlowMart <noreply@glowmart.com>'


import os
from pathlib import Path
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

# ================= SECURITY =================
SECRET_KEY = 'django-insecure-zedp_=pj+frk-x5*y$dsqk0%*50rk1kyddg=9(-4-h$*(2-hjj'

DEBUG = False

ALLOWED_HOSTS = [
    'glow-mart-backend-1.onrender.com',
    '.onrender.com',
    'hypermodest-irena-washy.ngrok-free.dev',
    'localhost',
    '127.0.0.1',
]

# ================= CORS SETTINGS =================
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "https://glow-mart.vercel.app",
    "https://glow-mart-frontend.vercel.app",
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:5500",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "https://hypermodest-irena-washy.ngrok-free.dev",
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400

# ================= CSRF =================
CSRF_TRUSTED_ORIGINS = [
    "https://glow-mart.vercel.app",
    "https://glow-mart-frontend.vercel.app",
    "https://hypermodest-irena-washy.ngrok-free.dev",
    "https://glow-mart-backend-1.onrender.com",
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400
SESSION_COOKIE_HTTPONLY = True

SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SAMESITE = 'None'

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'

APPEND_SLASH = True

# ================= ASGI / CHANNELS =================
ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# ================= INSTALLED APPS =================
INSTALLED_APPS = [
    'daphne',
    'corsheaders',
    'channels',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'sslserver',

    'dashboard',
    'inventory',
    'notifications',
    'orders',
    'reports',
    'users',
    'mpesa',
    'settings',
]

# ================= MIDDLEWARE (FIXED ORDER) =================
MIDDLEWARE = [
    'backend.middleware.ForceCorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    # TEMP SAFETY (prevents redirect/CSRF loops on Render)
    # 'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

# ================= TEMPLATES =================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# ================= DATABASE =================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ================= AUTH =================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# ================= INTERNATIONALIZATION =================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# ================= STATIC / MEDIA =================
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ================= REST FRAMEWORK =================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ================= JWT =================
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ================= M-PESA =================
MPESA_API_URL = 'https://sandbox.safaricom.co.ke'

MPESA_CONFIG = {
    'CONSUMER_KEY': 'DiyO3HgTpc5PuM1xRNdBbXppU7YWE1vuYnlvGZMRBVwzwZcE',
    'CONSUMER_SECRET': '23XZzrSz9gs4hg5eRsTXvp3oYHGF9OvRBIZQafef14SOFlpStiyfAA070pR4MrQG',
    'BUSINESS_SHORTCODE': '174379',
    'PASSKEY': 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
    'CALLBACK_URL': 'https://glow-mart-backend-1.onrender.com/api/mpesa/callback/',
    'TIMEOUT_URL': 'https://glow-mart-backend-1.onrender.com/api/mpesa/timeout/',
    'RESULT_URL': 'https://glow-mart-backend-1.onrender.com/api/mpesa/result/',
}

# ================= ORDER STATUSES =================
ORDER_STATUS_CHOICES = [
    ('pending', 'Pending'),
    ('processing', 'Processing'),
    ('completed', 'Completed'),
    ('cancelled', 'Cancelled'),
    ('refunded', 'Refunded'),
]

PAYMENT_STATUS_CHOICES = [
    ('pending', 'Pending'),
    ('processing', 'Processing'),
    ('completed', 'Completed'),
    ('failed', 'Failed'),
    ('refunded', 'Refunded'),
]

# ================= LOGGING =================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# ================= SECURITY (FIXED FOR RENDER) =================
if not DEBUG:
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = None
    USE_X_FORWARDED_HOST = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    SECURE_HSTS_SECONDS = 0

# ================= EMAIL =================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = 'GlowMart <noreply@glowmart.com>'